version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-northeast-2)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t gstalktset:latest .
      - docker tag gstalktset:latest 723910361729.dkr.ecr.ap-northeast-2.amazonaws.com/gstalktset:latest           
      
         
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push gstalktset:latest 723910361729.dkr.ecr.ap-northeast-2.amazonaws.com/gstalktset:latest
      - echo Writing image definitions file...
      - printf '[{"name":"testcontainer","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json


artifacts:
  files:
    - imagedefinitions.json
    - taskdef.json 
    - appspec.yml
  discard-paths: yes


